-
  name: 'To run commands on target server'
  hosts: all
  tasks:
    -
      name: 'Displaying target server hosts file'
      command: cat /etc/hosts
      register: output1
    -
      name: 'Displaying disk filesystem'
      command: df -hT
      register: output2
    -
      name: 'Displaying memory utilization'
      command: free -h
      register: output3
    - debug:
          var: "{{ item }}.stdout_lines"
      loop:
          - output1
          - output2
          - output3
