-
  name: 'Execute a script on all web server nodes'
  hosts: web_nodes
  tasks:
      - name: 'Execute a script on all web server nodes'
        script: /tmp/restart_webserver.sh
        register: result
      - debug: var="{{ result }}.stdout_lines"
