# Here we will learn how to use variables in Ansible playbook YAML file
# The variables are defined in double curly braces and should be enclosed within
# quotes. for example '{{ variable_name }}'

-
  name: 'Update the DNS server entry in target servers'
  hosts: web_nodes
  vars:
      car_model: 'BMW M3'
      country: 'India'
      title: 'DevOps Engineer'
  tasks:
    - name: 'Update the entry in /etc/hosts'
      lineinfile:
          path: /etc/resolv.conf
          line: 'nameserver {{ ip_address }}'
    - name: 'Disable SNMP port'
      firewalld:
          port: '{{ snmp_port }}'
          permanent: true
          state: disabled
    - name: 'Print my car model'
      command: 'echo "My car model name is {{ car_model }}"'
    - name: 'Print my country'
      command: 'echo "I live in {{ country }}"'
    - name: 'Print my work title'
      command: 'echo "I work as a {{ title }}"'
